// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://gdaipkiojgaiuslzgjsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkYWlwa2lvamdhaXVzbHpnanN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNDIxMzgsImV4cCI6MjA1OTYxODEzOH0.k5pY1Jxq104LuvJQVukyMmGyTX0Ztp2nyxbFDGzN2iA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);